### ISSUE TITLE
Enabling Eager Execution

### ISSUE THREAD

**Issue by chris-kehl** [Apress/advanced-applied-deep-learning#2]
import tensorflow as tf
tf.enable_eager_execution()

book shows this code but it errors out.
i guess in Colab it's already installed

**Comment by michelucci** [comment]
Hi Chris,
if you try it now in google colab you will get an error, since the standard version of TensorFlow in Google Colab is 2 today. For example try

```
import tensorflow as tf
print(tf.__version__)
```

and you will get

`2.2.0-rc3`

You can do the following to revert to version 1.X

```
%tensorflow_version 1.x
import tensorflow as tf
print(tf.__version__)
```

Now 

`tf.enable_eager_execution()`

will work. Hope that helps.

Best, Umberto
